version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      - how-are-you-db
  how-are-you-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/conf.cnf:/etc/mysql/conf.d/my.cnf"
    container_name: how_are_you_db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
